### ISSUE TITLE
RDFRefine - can't access imported ontology?

### ISSUE THREAD

**Issue by moamer-dev** [AtesComp/rdf-transform#12]
I'm using OpenRefine v.3.5.2  and its extension "rdf-extension v.1.3.1". I'm trying to import ontologies like dbpedia and schema. When I add prefix and insert the URI, it gives me no problem. However, when i try to access its properties it says: 'Not in the imported vocabulary definition.' I tried ti upload the ontology.owl as a local file and the same issue still exist. Could you help with that?

**Comment by AtesComp** [comment]
I don't work on the **RDF extension**, only RDF Transform.  The RDF extension had many issues, like the Lucene engine processing (an underlying problem related to yours).  That's why I redeveloped it as RDF Transform.  You can try it.  You will need to upgrade Java (JDK is easiest) to at least 11.  I would also suggest using OpenRefine 3.6-beta2 with it as the Java version bundled is upgraded to 11...unless you're using Linux.

Look at the "PredefinedVocabs" support file down in the extension 's directory to set up automatic vocab loading.

With debugging on (if you like), you should see RDF Transform downloading the ontology (or load from file) and also when you try to use it.

There is one problem with the latest released RDF Transform not processing literals beyond a root node connection when in Record mode (see #11).  The latest code has fixed the problem but I still need to create a release for it.
